export { default as App } from "./App/App";
export { default as Home } from "./Home/Home";
export { default as Login } from "./Login/Login";
export { default as Navbar } from "./Navbar/Navbar";
export { default as NewPostForm } from "./NewPostForm/NewPostForm";
export { default as NotAllowed } from "./NotAllowed/NotAllowed";
export { default as NotFound } from "./NotFound/NotFound";
export { default as Post } from "./Post/Post";
export { default as PostDetail } from "./PostDetail/PostDetail";
export { default as ProtectedRoute } from "./ProtectedRoute/ProtectedRoute";
export { default as Register } from "./Register/Register";
export { default as Stars } from "./Stars/Stars";
export { default as StarsInput } from "./StarsInput/StarsInput";
export { default as Facebook } from "./Icons/Facebook"
export { default as Instagram } from "./Icons/Instagram"
export { default as Twitter } from "./Icons/Twitter"